
import { Student, Weekday } from './types';

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'S001',
    fullName: 'Yuvathee',
    dob: '2019-01-31',
    fatherName: 'Dhaneshkumar',
    motherName: 'Vinotha',
    phone: '9655634554',
    address: '5, Aranmanipudur 1st street tirupur',
    schoolName: 'FNIS',
    grade: 'Grade 2',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S002',
    fullName: 'Aarurran Ashwin',
    dob: '2019-09-16',
    fatherName: 'Ashwin',
    motherName: 'Nivedhaa',
    phone: '9787001443',
    address: 'Amarjothi As nagar Kangeyam road Tirupur',
    schoolName: 'Nachiyar Padasala',
    grade: 'Grade-1',
    assignedDays: [Weekday.Monday, Weekday.Wednesday],
    status: 'Active'
  },
  {
    id: 'S003',
    fullName: 'S. Mithran',
    dob: '2018-11-02',
    fatherName: 'P. Sivakumar',
    motherName: 'S. Aruna',
    phone: '9443478756',
    address: '3A/40 RVE Nagar South, Rakkiyapalayam Cross, Kangayam Road, Tirupur-641 604',
    schoolName: 'The Home School',
    grade: 'Grade 2',
    assignedDays: [Weekday.Monday, Weekday.Wednesday],
    status: 'Active'
  },
  {
    id: 'S004',
    fullName: 'Prithikaa R',
    dob: '2018-09-16',
    fatherName: 'Rajaram S',
    motherName: 'Hema R',
    phone: '9884891876',
    address: '41/121, Amarjothi AS Nagar, Kangeyam Road, Tiruppur - 641604',
    schoolName: 'Ananta Veda International School',
    grade: 'Grade 2',
    assignedDays: [Weekday.Monday, Weekday.Wednesday],
    status: 'Active'
  },
  {
    id: 'S005',
    fullName: 'SANURAM K',
    dob: '2012-10-02',
    fatherName: 'KULOTHUNGAN R',
    motherName: 'SARANYA A T',
    phone: '9786369968',
    address: '5 KURUNJI NAGARVEXT, SHERIFF COLONY, TIRUPUR 641604',
    schoolName: 'FNIS NEWGEN SCHOOL',
    grade: 'Std VIII',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S006',
    fullName: 'Sanjheev.K',
    dob: '2018-08-12',
    fatherName: 'S. kumaresan',
    motherName: 'V. Saranya',
    phone: '9789235164',
    address: '165,LBP colony,PWD campus, near trends, Tiruppur road, kangeyam',
    schoolName: 'Euro kids & Republic Central school',
    grade: '2nd grade',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S007',
    fullName: 'B. Megnaa',
    dob: '2019-05-13',
    fatherName: 'R. Boobesh',
    motherName: 'J.V. Bhuvaneswari',
    phone: '9629333750',
    address: 'Flat 203, block 6, KRC dakshin chitra apartment, gandhi nagar, tirupur 641603',
    schoolName: 'Cotton valley school',
    grade: '1st std',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S008',
    fullName: 'Aadyamadan',
    dob: '2019-06-02',
    fatherName: 'B. madhan',
    motherName: 'M. santhiya',
    phone: '9597427275',
    address: '8/369, gandhinagar tirupur',
    schoolName: 'Indian public school',
    grade: 'Grade 1',
    assignedDays: [Weekday.Monday, Weekday.Wednesday],
    status: 'Active'
  },
  {
    id: 'S009',
    fullName: 'K R Krithikk vel',
    dob: '2010-11-23',
    fatherName: 'S Rangasamy',
    motherName: 'R Priya',
    phone: '9443042025',
    address: '6, km nagar main road velliangadu Tirupur 641604',
    schoolName: 'Nachiyar padasala international school',
    grade: 'Grade 10',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S010',
    fullName: 'Janarthana.R.D',
    dob: '2016-06-23',
    fatherName: 'Ramesh.C',
    motherName: 'Devi Priya.K',
    phone: '9842580815',
    address: '102-84 kuppagoundanvalasu, Aalambadi (post), Chennimalai Road, Aalambadi, Kangeyam, Tiruppur',
    schoolName: 'Agastya Academy',
    grade: '4th std',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S011',
    fullName: 'B.V. DHANU MITRAN',
    dob: '2017-06-17',
    fatherName: 'P. BHUVANESHWARAN',
    motherName: 'S. VIDHYA',
    phone: '7598005888',
    address: 'R.K. AVENUE, T.S.K. MARAGATHAMAL LAYOUT, VELIYANKADU, TIRUPUR-641608',
    schoolName: 'FRONTLINE NEWGEN INTERNATIONAL SCHOOL',
    grade: '3-B',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S012',
    fullName: 'K S MAGHIZHAN',
    dob: '2020-12-03',
    fatherName: 'S SABARISHWARAN',
    motherName: 'BL REKHA',
    phone: '8973173584',
    address: '221, Tiruppur Road, Kangayam',
    schoolName: 'Nachiyar padasala',
    grade: 'LKG',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S013',
    fullName: 'L Saisaran',
    dob: '2012-06-20',
    fatherName: 'S Vignesh',
    motherName: 'T Lavanya',
    phone: '8754011432',
    address: 'Flat 1G, Red Rose apartment, Uthukuli Road, Tirupur - 641601',
    schoolName: 'PEM SCHOOL',
    grade: 'VIII',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S014',
    fullName: 'H.S. Mrithvik',
    dob: '2019-03-19',
    fatherName: 'Hariharasudhan',
    motherName: 'Srividhya',
    phone: '7708189999',
    address: '7, Vega duplex 2nd floor K.N.S garden kangeyam road Tirupur',
    schoolName: 'Advaita international school',
    grade: 'Grade 1',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S015',
    fullName: 'A. Tamil Iniyan',
    dob: '2014-12-27',
    fatherName: 'S. Angusamy',
    motherName: 'S. Sindhu',
    phone: '9943256302',
    address: '333B, Aruljothi nagar, Kallangadu, Tirupur -4',
    schoolName: 'Frontline Newgen International School',
    grade: '6',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S016',
    fullName: 'Venba Ashwin',
    dob: '2019-09-14',
    fatherName: 'A R Ashwin',
    motherName: 'A Priyadarshini',
    phone: '9444113034',
    address: 'No.209, Tirupur Road, Kangayam-638701',
    schoolName: 'Agastya Academy, Arachalur',
    grade: 'Grade 1',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S017',
    fullName: 'Vihaan Vigneshvar', // Vihan
    dob: '2019-10-16',
    fatherName: 'Vigneshvar',
    motherName: 'Mirudhulaa',
    phone: '9942177020',
    address: 'PS Avenue, Aishwarya gardens, Sathyamoorthy nagar road, Kangeyam road, Tirupur 641604',
    schoolName: 'Cotton Valley school',
    grade: 'Grade 1',
    assignedDays: [Weekday.Monday, Weekday.Wednesday],
    status: 'Active'
  },
  {
    id: 'S018',
    fullName: 'Siddarth S',
    dob: '2013-10-25',
    fatherName: 'Sathya Prabhu S',
    motherName: 'Karpaga Gowthami',
    phone: '9994462434',
    address: 'No.6 bharathiyar nagar 2nd street Velliangadu Tirupur 641 604',
    schoolName: 'Frontline Millennium Shool(FMS)',
    grade: '6A',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S019',
    fullName: 'L visruthaa',
    dob: '2020-10-07',
    fatherName: 'P Leelakrishnan',
    motherName: 'L Subanandhini',
    phone: '9043608795',
    address: '1/100 Arasan thottam Nocchipalayam veerapandi po Tirupur',
    schoolName: 'Sri Chaitanya techno school',
    grade: 'UKG',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S020',
    fullName: 'G.R. Mirthuni',
    dob: '2018-11-29',
    fatherName: 'S. Raghuraman',
    motherName: 'J. Gayathri',
    phone: '9600645268',
    address: '17/1, sathyamoorthy nagar 2nd Street kangeyam road',
    schoolName: 'Ananta veda international school',
    grade: 'Grade 2',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S021',
    fullName: 'Aradhana',
    dob: '2015-04-24',
    fatherName: 'Kuppuraj',
    motherName: 'Gowthami',
    phone: '7339271429',
    address: '152,7th Street,ctc colony, dharapuram road trippur 641606',
    schoolName: 'Avis school',
    grade: '4th',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S022',
    fullName: 'Sunmahilan K',
    dob: '2019-09-15',
    fatherName: 'Kanagaraj R',
    motherName: 'Kalaivani S',
    phone: '8525000887',
    address: '4/404, T.Andipalayam , Thonghutipalayam, Tirupur',
    schoolName: 'Frontline Millennium School',
    grade: '1',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S023',
    fullName: 'Aadvik.D',
    dob: '2015-12-23',
    fatherName: 'Dharwish',
    motherName: 'Aruthra A',
    phone: '9047590003',
    address: '7/2,sheriff colony kurinji nagar extension,Tirupur-641604',
    schoolName: 'Lokhaa',
    grade: 'Grade-4',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S024',
    fullName: 'D. aathirra', // Athithi
    dob: '2014-01-03',
    fatherName: 'Nsn. dhanapal',
    motherName: 'D. vindhya vasini',
    phone: '9942711111',
    address: 'Nsn oil mill, 4/114 neikkaranpalayam, alambadi post, kangayam -638701, tirupur',
    schoolName: 'Cs academy',
    grade: '6',
    assignedDays: [Weekday.Monday, Weekday.Wednesday],
    status: 'Active'
  },
  {
    id: 'S025',
    fullName: 'D. atith', // Ayan
    dob: '2018-07-02',
    fatherName: 'Nsn dhanapal',
    motherName: 'D. vindhya vasini',
    phone: '9942711111',
    address: 'Nsn oil mill, 4/114 neikkaranpalayam, alambadi post, kangayam -638701, tirupur',
    schoolName: 'Cs academy',
    grade: '2',
    assignedDays: [Weekday.Monday, Weekday.Wednesday],
    status: 'Active'
  },
  {
    id: 'S026',
    fullName: 'S.K. Atharva',
    dob: '2014-05-25',
    fatherName: 'Karthikeyan',
    motherName: 'Sangeetha',
    phone: '9789774944',
    address: '19B Block Jawahar Nagar Sundamedu Murugampalayam Tirupur',
    schoolName: 'Front line international school',
    grade: 'VII',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S027',
    fullName: 'R. THAMIZH INIYAN', // Aruthan
    dob: '2019-03-23',
    fatherName: 'P. Ramesh Kumar',
    motherName: 'M. Yoga Shalini',
    phone: '9894544888',
    address: '3/205(2) selvapuram malayampalayam, Ganapathy Palayam post Tiruppur 641605',
    schoolName: 'Nachiyar padasala international',
    grade: 'Grade 1',
    assignedDays: [Weekday.Monday, Weekday.Wednesday],
    status: 'Active'
  },
  {
    id: 'S028',
    fullName: 'R.B. Darshan',
    dob: '2014-07-02',
    fatherName: 'A. Ramesh',
    motherName: 'R. Bharathi',
    phone: '9940305231',
    address: '4/8-1, kurunji nagar EXTN, 2nd st, Avinashiappa Layout, Tirupur - 641604',
    schoolName: 'Frontline international new gen school',
    grade: '6',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S029',
    fullName: 'V. Krishiv Nilan',
    dob: '2021-07-10',
    fatherName: 'Vigneshkumar',
    motherName: 'Rithanya',
    phone: '8870005512',
    address: '46, Kpn colony, Tirupur-641601',
    schoolName: 'Cotten valley',
    grade: 'LKG',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S030',
    fullName: 'Dhassarath T',
    dob: '2015-12-08',
    fatherName: 'Thirumurthy G',
    motherName: 'Malathi T',
    phone: '9965979833',
    address: '32c, 5th street, Ayyasamy colony, Kangayam, Tiruppur district 638701',
    schoolName: 'RVB, Nattarpalayam, Kangayam',
    grade: '5',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S031',
    fullName: 'D. Dhyan Maadhav', // Diyan
    dob: '2020-10-29',
    fatherName: 'Dinesh Kumar',
    motherName: 'Gowthami',
    phone: '9843416431',
    address: '46, KPN Colony, 3rd Street, Tirupur- 641601',
    schoolName: 'Frontline New Gen International School',
    grade: 'Jr KG',
    assignedDays: [Weekday.Monday, Weekday.Wednesday],
    status: 'Active'
  },
  {
    id: 'S032',
    fullName: 'Harishva',
    dob: '2015-09-09',
    fatherName: 'Prakash',
    motherName: 'Kiruthika',
    phone: '9788010101',
    address: '157, kinathan thottam, dheeran nagar, palayakottai road, kangayam',
    schoolName: 'Agastiya academy',
    grade: '5',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S033',
    fullName: 'Dhruventhan', // Dhuru
    dob: '2021-02-08',
    fatherName: 'Vignesh',
    motherName: 'Anu',
    phone: '9442242292',
    address: '133 Dharapuram Road Tirupur',
    schoolName: 'Little Mahilam',
    grade: 'Junior Kg',
    assignedDays: [Weekday.Monday, Weekday.Wednesday],
    status: 'Active'
  },
  {
    id: 'S034',
    fullName: 'J.N. Viyash',
    dob: '2014-10-26',
    fatherName: 'S. Nallasivam',
    motherName: 'V. Jamuna',
    phone: '9942555527',
    address: '11/15 V.O.C nagar 3rd street ,Kongu main road, ranganathapuram, Tiruppur',
    schoolName: 'Frontline NewGen International School',
    grade: 'Grade 6',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S035',
    fullName: 'SASHVINTH SHRI Y V',
    dob: '2011-07-28',
    fatherName: 'Yuvaraj E',
    motherName: 'Sathiya Y',
    phone: '9791360899',
    address: '2/487 sri sowdeswari nagar veerapandi po tirupur',
    schoolName: 'Front line cbse school',
    grade: '9',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S036',
    fullName: 'Mukhilesh',
    dob: '2018-03-28',
    fatherName: 'Murali',
    motherName: 'Gomathi',
    phone: '7604951005',
    address: '1/373(1) Kallangadu 1st Street, Tiruppur - 5',
    schoolName: 'Sri Chaitanya Techno School',
    grade: '3',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S037',
    fullName: 'Sakunthan K S',
    dob: '2014-08-13',
    fatherName: 'Kathirvel P',
    motherName: 'Suganya L',
    phone: '6374780746',
    address: '4, puraiyagoundenvalasu, Parenjervali post, Kangayam 638701',
    schoolName: 'Vivekanandha Academy',
    grade: 'VI',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S038',
    fullName: 'A.S Asmitha',
    dob: '2018-05-28',
    fatherName: 'M. Anand',
    motherName: 'A. Annusuya',
    phone: '9894809137',
    address: '114 B Kovai road Kangayem 638701',
    schoolName: 'Vivekanandha Academy',
    grade: 'Grade 2',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S039',
    fullName: 'Thulirmathi.V',
    dob: '2013-03-07',
    fatherName: 'P. Vadivel',
    motherName: 'K. Jayabharathi',
    phone: '9487519868',
    address: '9G, sowdambigai nagar, vaikalmedu, tirupur road, kangayam',
    schoolName: 'RVB Rashtriya vidhya bhavan kangayam',
    grade: '7 standard',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S040',
    fullName: 'G S Mithiran',
    dob: '2016-04-09',
    fatherName: 'Sathish Kumar p',
    motherName: 'Gowthami s',
    phone: '9585762477',
    address: '333 main road kangayam',
    schoolName: 'Vevekandha senior secondary school',
    grade: '4',
    assignedDays: [],
    status: 'Active'
  }
];
