
import { Student, Weekday } from './types';

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'S001',
    fullName: 'Yuvathee',
    dob: '2019-01-31',
    fatherName: 'Dhaneshkumar',
    motherName: 'Vinotha',
    phone: '9655634554',
    address: '5, Aranmanipudur 1st street tirupur',
    schoolName: 'FNIS',
    grade: 'Grade 2',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S017',
    fullName: 'Vihaan Vigneshvar (Vihan)',
    dob: '2019-10-16',
    fatherName: 'Vigneshvar',
    motherName: 'Mirudhulaa',
    phone: '9942177020',
    address: 'PS Avenue, Aishwarya gardens, Sathyamoorthy nagar road, Kangeyam road, Tirupur 641604',
    schoolName: 'Cotton Valley school',
    grade: 'Grade 1',
    assignedDays: [Weekday.Monday, Weekday.Wednesday],
    status: 'Active'
  },
  {
    id: 'S003',
    fullName: 'S. Mithran',
    dob: '2018-11-02',
    fatherName: 'P. Sivakumar',
    motherName: 'S. Aruna',
    phone: '9443478756',
    address: '3A/40 RVE Nagar South, Rakkiyapalayam Cross, Kangayam Road ,Tirupur-641 604',
    schoolName: 'The Home School',
    grade: 'Grade 2',
    assignedDays: [Weekday.Monday, Weekday.Wednesday],
    status: 'Active'
  },
  {
    id: 'S004',
    fullName: 'Prithikaa R (Preethika)',
    dob: '2018-09-16',
    fatherName: 'Rajaram S',
    motherName: 'Hema R',
    phone: '9884891876',
    address: '41/121, Amarjothi AS Nagar, Kangeyam Road, Tiruppur - 641604',
    schoolName: 'Ananta Veda International School',
    grade: 'Grade 2',
    assignedDays: [Weekday.Monday, Weekday.Wednesday],
    status: 'Active'
  },
  {
    id: 'S024',
    fullName: 'D. Aathirra (Athithi)',
    dob: '2014-01-03',
    fatherName: 'Nsn. dhanapal',
    motherName: 'D. vindhya vasini',
    phone: '9942711111',
    address: 'Nsn oil mill, 4/114 neikkaranpalayam, alambadi post, kangayam -638701, tirupur',
    schoolName: 'Cs academy',
    grade: '6',
    assignedDays: [Weekday.Monday, Weekday.Wednesday],
    status: 'Active'
  },
  {
    id: 'S025',
    fullName: 'D. Atith (Ayan)',
    dob: '2018-07-02',
    fatherName: 'Nsn dhanapal',
    motherName: 'D. vindhya vasini',
    phone: '9942711111',
    address: 'Nsn oil mill, 4/114 neikkaranpalayam, alambadi post, kangayam -638701, tirupur',
    schoolName: 'Cs academy',
    grade: '2',
    assignedDays: [Weekday.Monday, Weekday.Wednesday],
    status: 'Active'
  },
  {
    id: 'S027',
    fullName: 'R. Thamizh Iniyan (Aruthan)',
    dob: '2019-03-23',
    fatherName: 'P. Ramesh Kumar',
    motherName: 'M. Yoga Shalini',
    phone: '9894544888',
    address: '3/205(2) selvapuram malayampalayam, Ganapathy Palayam post Tiruppur 641605',
    schoolName: 'Nachiyar padasala international',
    grade: 'Grade 1',
    assignedDays: [Weekday.Monday, Weekday.Wednesday],
    status: 'Active'
  },
  {
    id: 'S031',
    fullName: 'D. Dhyan Maadhav (Diyan)',
    dob: '2020-10-29',
    fatherName: 'Dinesh Kumar',
    motherName: 'Gowthami',
    phone: '9843416431',
    address: '46, KPN Colony, 3rd Street, Tirupur- 641601',
    schoolName: 'Frontline New Gen International School',
    grade: 'Jr KG',
    assignedDays: [Weekday.Monday, Weekday.Wednesday],
    status: 'Active'
  },
  {
    id: 'S033',
    fullName: 'Dhruventhan (Dhuru)',
    dob: '2021-02-08',
    fatherName: 'Vignesh',
    motherName: 'Anu',
    phone: '9442242292',
    address: '133 Dharapuram Road Tirupur',
    schoolName: 'Little Mahilam',
    grade: 'Junior Kg',
    assignedDays: [Weekday.Monday, Weekday.Wednesday],
    status: 'Active'
  },
  {
    id: 'S002',
    fullName: 'Aarurran Ashwin',
    dob: '2019-09-16',
    fatherName: 'Ashwin',
    motherName: 'Nivedhaa',
    phone: '9787001443',
    address: 'Amarjothi As nagar Kangeyam road Tirupur',
    schoolName: 'Nachiyar Padasala',
    grade: 'Grade-1',
    assignedDays: [Weekday.Monday, Weekday.Wednesday],
    status: 'Active'
  },
  {
    id: 'S005',
    fullName: 'SANURAM K',
    dob: '2012-10-02',
    fatherName: 'KULOTHUNGAN R',
    motherName: 'SARANYA A T',
    phone: '9786369968',
    address: '5 KURUNJI NAGARVEXT, SHERIFF COLONY, TIRUPUR 641604',
    schoolName: 'FNIS NEWGEN SCHOOL',
    grade: 'Std VIII',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S006',
    fullName: 'Sanjheev.K',
    dob: '2018-08-12',
    fatherName: 'S. kumaresan',
    motherName: 'V. Saranya',
    phone: '9789235164',
    address: '165,LBP colony,PWD campus, near trends, Tiruppur road, kangeyam',
    schoolName: 'Euro kids & Republic Central school',
    grade: '2nd grade',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S010',
    fullName: 'Janarthana.R.D',
    dob: '2016-06-23',
    fatherName: 'Ramesh.C',
    motherName: 'Devi Priya.K',
    phone: '9842580815',
    address: '102-84 kuppagoundanvalasu, Aalambadi (post), Chennimalai Road, Aalambadi, Kangeyam, Tiruppur',
    schoolName: 'Agastya Academy',
    grade: '4th std',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S014',
    fullName: 'H.S. Mrithvik',
    dob: '2019-03-19',
    fatherName: 'Hariharasudhan',
    motherName: 'Srividhya',
    phone: '7708189999',
    address: '7, Vega duplex 2nd floor K.N.S garden kangeyam road Tirupur',
    schoolName: 'Advaita international school',
    grade: 'Grade 1',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S023',
    fullName: 'Aadvik.D',
    dob: '2015-12-23',
    fatherName: 'Dharwish',
    motherName: 'Aruthra A',
    phone: '9047590003',
    address: '7/2,sheriff colony kurinji nagar extension,Tirupur-641604',
    schoolName: 'Lokhaa',
    grade: 'Grade-4',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S035',
    fullName: 'SASHVINTH SHRI Y V',
    dob: '2011-07-28',
    fatherName: 'Yuvaraj E',
    motherName: 'Sathiya Y',
    phone: '9791360899',
    address: '2/487 sri sowdeswari nagar veerapandi po tirupur',
    schoolName: 'Front line cbse school',
    grade: '9',
    assignedDays: [],
    status: 'Active'
  },
  {
    id: 'S040',
    fullName: 'G S Mithiran',
    dob: '2016-04-09',
    fatherName: 'Sathish Kumar p',
    motherName: 'Gowthami s',
    phone: '9585762477',
    address: '333 main road kangayam',
    schoolName: 'Vevekandha senior secondary school',
    grade: '4',
    assignedDays: [],
    status: 'Active'
  }
];
